### ISSUE TITLE
TST algorithm doesn't work properly

### ISSUE THREAD

**Issue by mczajk83** [JohnCEarls/AUREA#31]
Results of TST depend on assignment to classes in Class definition. It can be observed in imbalance classes but also in your example file. If cancer smoker is assigned to Class 1 and cancer free smoker is assigned to Class 2 the evaluated performance results for TST are different if we assign classes oppositely (cancer to Class 2 and no cancer to Class1).

I think that the algorithm may not work at all. 

Tested with latest  AUERA windows installation 32 and 64bit.

**Comment by JohnCEarls** [comment]
Thanks for your interest.  You are the first person outside of my lab that I am aware of who is using this. :)

I have run tests where the classes are exchanged and I am getting consistent results on GDS2771 (the cancer study I believe you are referencing), see bottom.  I would appreciate it if you would send me the saved results you are getting(i.e. after you train, click save in the popup menu). 

Once again, glad to hear someone is trying to use AUREA.

When I save the results from GDS2771 I get:

# C2=cancer, C1=noncancer

acc: 0.72192513369
g1=SLC5A1-206628_at g2=MYOF-217518_at   g3=C6-210168_at
order   P(order|class1) P(order|class2) 
Triplet 1
g1<g2<g3    0.0444444444444 0.0103092783505
g1<g3<g2    0.0111111111111 0.0
g2<g1<g3    0.2 0.412371134021
g2<g3<g1    0.188888888889  0.412371134021
g3<g1<g2    0.177777777778  0.0
g3<g2<g1    0.377777777778   0.164948453608

# Settings

Data Settings
Data Folder:data
Bad Data Value:0.0
Gene Collision Rule:MAX
Gene Column:IDENTIFIER
Probe Column:ID_REF

# TST Settings

Row Key(genes/probes):probe
filters:10,10,10

and

# C1=cancer, C2=noncancer

@acc: 0.72192513369
g1=SLC5A1-206628_at g2=MYOF-217518_at   g3=C6-210168_at
order   P(order|class1) P(order|class2) 
Triplet 1
g1<g2<g3    0.0103092783505 0.0444444444444
g1<g3<g2    0.0 0.0111111111111
g2<g1<g3    0.412371134021   0.2
g2<g3<g1    0.412371134021  0.188888888889
g3<g1<g2    0.0 0.177777777778
g3<g2<g1    0.164948453608  0.377777777778

# Settings

Data Settings
Data Folder:data
Bad Data Value:0.0
Gene Collision Rule:MAX
Gene Column:IDENTIFIER
Probe Column:ID_REF

# TST Settings

Row Key(genes/probes):probe
filters:10,10,10

**Comment by mczajk83** [comment]
Hi,

I just wrote you a private message to you on gmail account - I hope you'll get it. 
The problem was with evaluating performance of TST method (the training classifiers works ok).

Best wishes
Marcin

**Comment by JohnCEarls** [comment]
Confirmed and critical.  Bug in c++ crossvalidation code.
